# Dependencias
FROM node:20-alpine as deps

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Builder - Construye la aplicación
FROM node:20-alpine as build

WORKDIR /usr/src/app

# Copiar de deps, los módulos de node
COPY --from=deps /usr/src/app/node_modules ./node_modules

# Copiar todo el código fuente de la aplicación (lo que no está definido en el .dockerignore)
COPY . .

# RUN npm run test (en caso de realizar tests)
RUN npm run build

RUN npm ci -f --only=production && npm cache clean --force

# Crear la imagen final de Docker
FROM node:20-alpine as prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules

# Copiar la carpeta de DIST
COPY --from=build /usr/src/app/dist ./dist

ENV NODE_ENV=production

USER node

EXPOSE 3000

CMD ["node", "dist/main.js"]